fix(ci): fixes quality workflow
error: rspec command is not finding any examples to test

cause: the folder of the spec files were not explicit

solution: added the spec folder to the rspec command